[project]
name = "world-model-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "ml-commons",
    "rl-commons",
    "my-rl-impl",
    "scikit-learn>=1.9.0",
    "torch>=2.12.0",
    "tqdm>=4.67.0",
]

[tool.uv.sources]
rl-commons = { git = "https://github.com/kieranparanjpe/rl-commons.git" }
ml-commons = { git = "https://github.com/kieranparanjpe/ml-commons.git" }
my-rl-impl = { git = "https://github.com/kieranparanjpe/My-RL-Impl.git" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src"]

